package fi.kroon.vadret.util

/**
 *  Widget Settings Keys
 */
const val LAST_CHECKED_WIDGET_KEY = "LAST_CHECKED_WIDGET_"
const val AUTOMATIC_LOCATION_MODE_WIDGET_KEY: String = "AUTOMATIC_LOCATION_MODE_WIDGET_"
const val THEME_MODE_WIDGET_KEY: String = "APP_THEME_MODE_WIDGET_"
const val UPDATE_INTERVAL_WIDGET_KEY: String = "UPDATE_INTERVAL_WIDGET_"
const val COUNTY_WIDGET_KEY: String = "COUNTY_WIDGET_"
const val LOCALITY_WIDGET_KEY: String = "LOCALITY_WIDGET_"
const val MUNICIPALITY_WIDGET_KEY: String = "MUNICIPALITY_WIDGET_"
const val LATITUDE_WIDGET_KEY: String = "LATITUDE_WIDGET_"
const val LONGITUDE_WIDGET_KEY: String = "LONGITUDE_WIDGET_"
const val FORECAST_FORMAT_WIDGET_KEY: String = "FORECAST_FORMAT_WIDGET_"
const val INITIALISED_STATUS_WIDGET_KEY: String = "INITIALISED_STATUS_WIDGET_"

/**
 *  App Settings Keys
 */
const val AUTOMATIC_LOCATION_MODE_KEY: String = "AUTOMATIC_LOCATION_MODE"
const val COUNTY_KEY: String = "COUNTY"
const val MUNICIPALITY_KEY: String = "MUNICIPALITY"
const val LOCALITY_KEY: String = "LOCALITY"
const val LATITUDE_KEY: String = "LATITUDE"
const val LONGITUDE_KEY: String = "LONGITUDE"
const val THEME_MODE_KEY: String = "APP_THEME_MODE"
const val LAST_CHECKED_KEY: String = "LAST_CHECKED"
const val LAST_CHECKED_RADAR_KEY: String = "LAST_CHECKED_RADAR"
const val DEFAULT_VALUE = "None"
const val DISTRICT_AVAILABLE_KEY = "DISTRICT_VIEW_AVAILABLE"
const val FEED_SOURCE_AVAILABLE_KEY = "FEED_SOURCE_AVAILABLE"
const val APP_WARNING_FILTER_SORT_ORDER_KEY = "APP_WARNING_FILTER_SORT_ORDER"
const val APP_AGGREGATED_FEED_LAST_CHECKED_KEY = "AGGREGATED_FEED_LAST_CHECKED"